[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "tg-gnn"
version = "0.1.0"
description = "Tigergraph GNN project"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [
    { name = "Zettabolt"}
]

keywords = ["graph", "gnn", "tigergraph"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]

# If you have direct dependencies, list them here:
dependencies = [
]

[project.optional-dependencies]
dev = [
    "pytest>=6.2.0"
]

[tool.setuptools.packages.find]
where = ["."]
